### ISSUE TITLE
Update for Spack 1.0 repos

### ISSUE THREAD

**Issue by viperML** [spack/schemas#2]
I believe the schemas should be updated for the new repo format of 1.0

```yaml
repos:
  builtin:
    git: https://github.com/spack/spack-packages.git
```
